import { cookies } from 'next/headers';
import { AlertIcon } from '../../components/icons/AlertIcon';

import { Insight } from '../../types/insight';

export const dynamic = 'force-dynamic';

export default async function InsightsPage() {
    let insights: Insight[] = [];
    let error = null;

    try {
        // 1. Extract the token from the secure Next.js Server Cookie
        const cookieStore = await cookies();
        const token = cookieStore.get('kh_os_token')?.value;

        if (!token) {
            throw new Error("Unauthorized: Please log in to view your insights.");
        }

        // 2. Attach it to the FastAPI request
        const aiServiceUrl = process.env.NEXT_PUBLIC_AI_SERVICE_URL || 'http://localhost:8000';
        const res = await fetch(`${aiServiceUrl}/insights`, {
            cache: 'no-store',
            headers: {
                'Authorization': `Bearer ${token}`, // 🔒 Secure payload!
                'Content-Type': 'application/json'
            }
        });

        if (!res.ok) {
            if (res.status === 401) throw new Error("Your session has expired. Please log in again.");
            throw new Error("Failed to fetch from AI Service");
        }

        const data = await res.json();
        insights = data.insights;
        console.log(`[InsightsPage] Successfully fetched ${insights.length} insights from AI Service.`);
    } catch (err: any) {
        error = err.message;
        console.error(`[InsightsPage] Error fetching insights:`, error);
    }

    return (
        <div className="w-full flex-1 flex flex-col pb-12 relative">
            <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-primary/10 rounded-full blur-[150px] pointer-events-none -z-10 animate-pulse-slow" />
            <div className="absolute top-40 left-0 w-[400px] h-[400px] bg-accent/5 rounded-full blur-[100px] pointer-events-none -z-10 animate-blob" />

            <div className="mb-12 relative z-10 animate-fade-in">
                <div className="inline-flex items-center justify-center px-4 py-1.5 mb-4 rounded-full bg-surface/50 border border-primary/30 backdrop-blur-md shadow-[0_0_15px_rgba(99,102,241,0.15)]">
                    <span className="w-2 h-2 rounded-full bg-primary mr-3 shadow-[0_0_8px_rgba(99,102,241,0.8)] animate-pulse"></span>
                    <span className="text-primary text-[10px] font-mono font-bold uppercase tracking-widest">
                        Module :: Intelligence Feed
                    </span>
                </div>
                <h1 className="text-4xl md:text-6xl font-extrabold tracking-tighter mb-4 text-transparent bg-clip-text bg-gradient-to-r from-white to-zinc-400">
                    Autonomous Brain
                </h1>
                <p className="text-lg text-zinc-400 max-w-2xl font-light">Real-time career roadmaps and active productivity coaching generated by your Gemini engine.</p>
            </div>

            {error && (
                <div className="bg-red-500/10 border border-red-500/30 text-red-400 p-4 rounded-xl mb-8 flex items-start backdrop-blur-md animate-slide-up">
                    <AlertIcon className="w-5 h-5 mr-3 flex-shrink-0 mt-0.5" />
                    <span className="font-mono text-sm tracking-wide">Unable to connect to the AI Service Brain: {error}</span>
                </div>
            )}

            <div className="grid gap-8 relative z-10">
                {insights.length === 0 && !error ? (
                    <div className="bg-surface/20 backdrop-blur-xl border border-white/5 border-dashed rounded-3xl flex flex-col items-center justify-center py-24 text-center relative overflow-hidden group">
                        <div className="absolute inset-0 bg-gradient-to-b from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
                        <div className="w-20 h-20 rounded-2xl bg-surface border border-white/10 flex items-center justify-center mb-6 relative z-10 shadow-inner group-hover:scale-110 transition-transform duration-500">
                            <span className="text-4xl">💤</span>
                        </div>
                        <h3 className="text-2xl font-bold text-white mb-2 relative z-10">No intelligence gathered yet</h3>
                        <p className="text-zinc-500 max-w-md font-light relative z-10 leading-relaxed">Complete an execution task in your workspace to wake up the AI and receive your first coaching insight.</p>
                    </div>
                ) : (
                    insights.map((insight: Insight) => {
                        // Fallback to career_roadmap for older test data
                        const type = insight.type || "career_roadmap";
                        const isRoadmap = type === "career_roadmap";
                        
                        const colorTheme = isRoadmap ? 'primary' : 'success';

                        return (
                            <div
                                key={insight._id}
                                className={`relative bg-surface/30 backdrop-blur-2xl border border-white/5 rounded-3xl p-6 md:p-10 shadow-[0_8px_32px_rgba(0,0,0,0.4)] flex flex-col transition-all duration-500 group overflow-hidden ${isRoadmap ? 'hover:border-primary/30' : 'hover:border-success/30'}`}
                            >
                                <div className={`absolute inset-0 bg-gradient-to-br opacity-0 group-hover:opacity-100 transition-opacity duration-700 ${isRoadmap ? 'from-primary/10 to-transparent' : 'from-success/10 to-transparent'}`} />

                                <div className={`absolute top-0 right-0 w-64 h-64 rounded-full blur-[80px] -translate-y-1/2 translate-x-1/3 pointer-events-none transition-opacity duration-700 ${isRoadmap ? 'bg-primary/20 opacity-50 group-hover:opacity-100' : 'bg-success/20 opacity-50 group-hover:opacity-100'}`} />

                                {/* Decorative HUD Elements */}
                                <div className={`absolute top-0 left-0 w-10 h-10 border-t-2 border-l-2 rounded-tl-3xl pointer-events-none ${isRoadmap ? 'border-primary/40' : 'border-success/40'}`} />
                                <div className={`absolute bottom-0 right-0 w-10 h-10 border-b-2 border-r-2 rounded-br-3xl pointer-events-none ${isRoadmap ? 'border-primary/40' : 'border-success/40'}`} />
                                
                                <div className="flex flex-col lg:flex-row lg:justify-between lg:items-start mb-8 gap-6 relative z-10">
                                    <div>
                                        <h3 className={`text-2xl font-bold mb-4 flex items-center tracking-tight ${isRoadmap ? 'text-white group-hover:text-primary transition-colors' : 'text-white group-hover:text-success transition-colors'}`}>
                                            {isRoadmap ? (
                                                <><span className="mr-3 text-3xl drop-shadow-[0_0_10px_rgba(255,255,255,0.3)]">🗺️</span> Career Roadmap Generated</>
                                            ) : (
                                                <><span className="mr-3 text-3xl drop-shadow-[0_0_10px_rgba(255,255,255,0.3)]">🎯</span> Productivity Coach</>
                                            )}
                                        </h3>

                                        {/* Dynamic Badges based on event type */}
                                        <div className="flex flex-wrap gap-3">
                                            {isRoadmap ? (
                                                <>
                                                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest px-3 py-1.5 bg-primary/10 text-primary border border-primary/30 rounded-lg shadow-[0_0_10px_rgba(99,102,241,0.2)]">
                                                        Role_Param: {insight.role || "Developer"}
                                                    </span>
                                                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest px-3 py-1.5 bg-surface/80 text-zinc-400 border border-white/10 rounded-lg shadow-inner">
                                                        User_Hash: {insight.userId.substring(0, 8)}
                                                    </span>
                                                </>
                                            ) : (
                                                <>
                                                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest px-3 py-1.5 bg-success/10 text-success border border-success/30 rounded-lg shadow-[0_0_10px_rgba(16,185,129,0.2)]">
                                                        Task_ID: {insight.task}
                                                    </span>
                                                    <span className="text-[10px] font-mono font-bold uppercase tracking-widest px-3 py-1.5 bg-surface/80 text-zinc-400 border border-white/10 rounded-lg shadow-inner">
                                                        Obj_ID: {insight.goal}
                                                    </span>
                                                </>
                                            )}
                                        </div>
                                    </div>

                                    <div className="text-[10px] text-zinc-500 font-mono uppercase tracking-widest bg-surface/50 backdrop-blur-md px-4 py-2 rounded-lg border border-white/10 flex-shrink-0 self-start shadow-inner">
                                        TRACE_ID: {insight._id.substring(0, 12)}
                                    </div>
                                </div>

                                <div className={`relative overflow-hidden rounded-2xl p-6 md:p-8 border bg-surface/50 backdrop-blur-md shadow-inner ${isRoadmap ? 'border-primary/20' : 'border-success/20'}`}>
                                    
                                    <div className={`absolute left-0 top-0 bottom-0 w-1 ${isRoadmap ? 'bg-primary' : 'bg-success'}`} />
                                    
                                    <div className="flex items-center mb-4 relative z-10">
                                        <span className={`w-2.5 h-2.5 rounded-full mr-3 shadow-[0_0_8px_currentColor] ${isRoadmap ? 'bg-primary animate-pulse text-primary' : 'bg-success animate-pulse text-success'}`}></span>
                                        <span className={`text-xs font-mono font-bold uppercase tracking-widest ${isRoadmap ? 'text-primary' : 'text-success'}`}>
                                            Gemini Intelligence Analysis
                                        </span>
                                    </div>
                                    <p className="text-zinc-300 leading-relaxed text-sm md:text-base relative z-10 font-light">
                                        {insight.ai_summary}
                                    </p>
                                    
                                    <div className={`absolute bottom-3 right-4 text-[9px] font-mono uppercase tracking-widest opacity-40 ${isRoadmap ? 'text-primary' : 'text-success'}`}>
                                        ANALYSIS_COMPLETE
                                    </div>
                                </div>
                            </div>
                        );
                    })
                )}
            </div>
        </div>
    );
}
